### PR TITLE
fix build against netbsd curses

### PR DESCRIPTION
**Pull request by rofl0r**
https://github.com/sabotage-linux/netbsd-curses/

### CODE REVIEW

**Comment by vigna** [comment]
Can you explain what is the problem with netbsd?

**Comment by rofl0r** [comment]
ncurses changed the tparm prototype to a variadic signature, while the original curses implementation uses the original ten-argument prototype:

see also https://linux.die.net/man/3/tparm

> X/Open Curses prototypes tparm with a fixed number of parameters, rather than a variable argument list. This implementation uses a variable argument list. Portable applications should provide 9 parameters after the format; zeroes are fine for this purpose.

**Comment by vigna** [comment]
Wow. Seriously there are _still_ systems with the non-variadic tparm()?!?

@utoddl : this for me can be merged—what's your opinion?

(Sorry for forgetting to read this in the last 8 months.)

**Comment by rofl0r** [comment]
> Wow. Seriously there are still systems with the non-variadic tparm()?!?

correct, that's why above quote specifically mentions that `Portable applications should provide 9 parameters after the format; zeroes are fine for this purpose`.

**Comment by utoddl** [comment]
@vigna Seems fine to me. Looks like the Right Thing to do.

**Pull request merged**
