### PR TITLE
Prevent Save action from writing to a file when opened read-only

### PR DESCRIPTION
**Pull request by abelbeck**
When viewing files read-only on an overlay filesystem, a user does not "muscle memory" from accidentally writing to the file.

### CODE REVIEW

**Comment by utoddl** [comment]
Interesting. So the problem is, we have a read-only flag that refers only to the buffer, but we don't have one that means "don't save this file". Your fix does take care of the obvious "oops, I hit save" error. We probably need to think about this a bit before we open a can of worms. You've clearly identified a real problem though, and this needs to be addressed. Thanks.

**Comment by abelbeck** [comment]
In my testing this PR appears to work, such as with:
```
ne foo1 --ro foo2 foo3
```
The `b->opt.read_only` and `b->filename` are in sync, and other SaveAll actions appear to be predicated with `save_all_modified_buffers()`.

**Comment by vigna** [comment]
Well, the change is entirely minimal, a one-liner: it disable save when the document is read-only.

The point is: what is the meaning of read-only? For me, it means that you cannot modify the *buffer* containing the file in ne. It doesn't mean you can't save it. If you want to make a *file* read-only, you have to use the facilities of the OS.

**Comment by abelbeck** [comment]
I would argue that since `--ro filename` is how a user uses this option, the filename should be read-only.  I understand internally the buffer is read-only, but why not extend this to the filename the user invoked ? Particularly if the fix is trivial.

Again, this is to protect against the user from accidentally saving the file, which would be a NoOp anyway ... except for an overlay/unionfs file system where a save may copy the file to the read-write layer.

Granted our project can maintain this trivial patch, but it seems upstream worthy to my eye.

**Comment by utoddl** [comment]
I routinely mark a buffer r/o so I can switch between the "original" and a copy that I'm modifying. It keeps me from inadvertently changing the wrong copy. Normally I don't intend to write such a r/o buffer to a file, and it'd be nice in this case if ne prevented such inadvertent writes. Also, we mark the buffer r/o when we load a read-only file into it. I don't think it would cause a problem if we extended a buffer's read-only flag to also mean "don't attempt to write to a file"... except maybe for the corner cases. For example, SaveAs to a new file name -- should that work for a r/o buffer? Note also that you can flip the r/o flag on an already modified buffer. Should that make a difference when it comes time to save? Maybe not. But issues like these are the can of worms I was referring to above.

**Comment by pepa65** [comment]
If Save to the original file would not work, that is reasonable, but if SaveAs doesn't work on a readonly file, that is undesirable. Maybe it should more properly be called a `--view` flag, where a buffer cannot be modified and the original file cannot be written to.

**Comment by abelbeck** [comment]
@pepa65 This PR only disables "Save" for a read-only buffer/file ... "SaveAs" is still permitted for a read-only buffer/file.  I think that is a good approach.

**Comment by utoddl** [comment]
As it stands, this PR still allows modified read-only buffers to be saved by a SaveAll action. (BTW, as Sebastiano has pointed out before, that's a bad name. It should have been something like SaveModifiedBuffers, but let's not conflate the issue.) Perhaps it would be better to enforce this "RO prevents saving" in the buffers.c:save_buffer_to_file() function. Then you get consistent behavior. SaveAs would need to handle the RO flag to give that exception.

**Comment by utoddl** [comment]
The more I look at it, the more I think that one line needs to be near the top of save_buffer_to_file() rather than in do_action(). It provides simple to explain and understand behavior: "RO prevents changing or saving of buffers." No special cases.

(Give me another day and I'll change my mind again. :)

**Comment by abelbeck** [comment]
@utoddl Though for "SaveAs" wouldn't you like to see the `DOCUMENT_IS_READ_ONLY` error before you went through the process of specifying a filename?  Then it still needs to be in `do_action()`.

**Comment by abelbeck** [comment]
In summary, may I propose two options:

A: (Per this PR)
```
Save:
actions.c -> do_action()
+ if (b->opt.read_only) return DOCUMENT_IS_READ_ONLY;

SaveAll/Exit/Quit: no change, save modified read-only files

SaveAs: no change
```
B:
```
Save:
actions.c -> do_action()
+ if (b->opt.read_only) return DOCUMENT_IS_READ_ONLY;

SaveAll/Exit/Quit: skip modified read-only files
buffers.c -> save_all_modified_buffers()
- if (b->is_modified) {
+ if (b->is_modified && !b->opt.read_only) {  /* Silently skip read-only */
buffers.c -> modified_buffers()
- if (b->is_modified) return true;
+ if (b->is_modified && !b->opt.read_only) return true;  /* Silently skip read-only */

SaveAs: no change
```
Note for "B", a file opened `--ro` can't be modified, so for this to occur the read-only must be set after the buffer is modified. Also note `actions.c` contains lines like:
```
if ((b->is_modified) && !request_response(b, info_msg[THIS_DOCUMENT_NOT_SAVED], false)) return ERROR;
```

**Comment by utoddl** [comment]
Can. Of. Worms.

Not at all interested in silently skipping modified buffers on exit. Never throw away users' work without their verification.

Let the RO flag either block saves, or not, but don't make special cases for, say, Save vs. SaveAs, Exit, or Quit. A prompt ("buffer is marked ReadOnly; save anyway?") would be okay-ish, but special cases will bite somebody. They are worse than the problem this is supposed to solve.

**Comment by abelbeck** [comment]
@utoddl I hear you.  So "A", a "C" alternative, or close this PR ?

**Comment by utoddl** [comment]
I still think it's a real problem that needs to be addressed. Maybe this PR with the right changes, or just as an open issue. Certainly keep your local change -- it's solving _your_ problem for the moment --  until we can settle on the right approach for these corner cases. Let's keep thinking about this though. Rushing to implementation is a recipe for regret.

**Comment by abelbeck** [comment]
@utoddl Fair enough.

The origin to this can-of-worms is the ability to mark a modified buffer RO.  If at that point the user must choose to save changes or clear the modified flag, then with this PR all the rest of the "saves" track the modified flag. Once RO it can't be modified.

**Comment by utoddl** [comment]
But it can be marked modified with the Modified command. Both of those flags can be changed by the user w/o regard for whether there are/were actual buffer changes or whether the corresponding file (if there is one) is effectively RO or RW. If we are to extend the meaning of a buffer's RO flag to mean we avoid saves, the question is how to do it consistently in the context of other flags while still maintaining the "element of least surprise". We're getting there.

**Pull request merged**
